include: "rules/index.smk"
include: "rules/clean.smk"
include: "rules/align.smk"

configfile: "config/config.yaml"

import pathlib
import re
from Bio import SeqIO

def get_barcodes():
    barcode_file = config["barcodes"]
    barcodes = []
    for record in SeqIO.parse(barcode_file, "fasta"):
        barcodes.append(record.id)
    return barcodes

def get_sample_metadata(path: str) -> dict[str, list[str]]:
    """
    Get sample metadata from a directory of fastq files
    :param path: path to directory of fastq files
    :return: a dictionary of sample names and their associated fastq files
    """
    # Initialise dictionary to store sample metadata
    samples = {}
    # Initialise pathlib object
    file_path = pathlib.Path(path)
    # Check if path is a directory
    if file_path.is_dir():

        # Iterate over files in directory
        for file in file_path.iterdir():
            # Check if file is a fastq file
            if file.suffixes in [[".fastq", ".gz"], [".fq", ".gz"], [".fastq"], [".fq"]]:
                # Split file name on first period
                name_parts = file.name.split(".", 1)
                # Remove _1 or _2 from sample name
                sample_name = re.sub(r"_[12]", "", name_parts[0])
                # Add sample name and file name to dictionary
                if sample_name in samples.keys():
                    samples[sample_name].append(file.name)
                else:
                    samples[sample_name] = [file.name]
    return samples

rule all:
    input:
        expand("resources/data/aligned/{sample}_{barcode}.sam", sample=get_sample_metadata(config["data"]).keys(), barcode=get_barcodes())
