# Sequencing technology, either 'illumina' or 'iontorrent'
technology: illumina

# Path to the reference genome
reference: resources/reference.fna

# Adapter sequence to be trimmed
adapter: AGATCGGAA

# Path to the barcodes used for demultiplexing
barcodes: resources/barcodes.fasta

# Minimum read length
min_read_length: 50

# PLATYPUS: Minimum number of supporting reads required before a variant candidate will be considered
platypus_min_reads: 2